var characters = {
	"Bayonetta": "bayonetta",
	"Bowser": "bowser",
	"Bowser Jr.": "bowser_jr",
	"Captain Falcon": "captain_falcon",
	"Charizard": "charizard",
	"Cloud": "cloud",
	"Corrin": "corrin",
	"Dark Pit": "dark_pit",
	"Diddy Kong": "diddy_kong",
	"Donkey Kong": "donkey_kong",
	"Dr. Mario": "dr_mario",
	"Duck Hunt": "duck_hunt",
	"Falco": "falco",
	"Fox": "fox",
	"Ganondorf": "ganondorf",
	"Greninja": "greninja",
	"Ice Climbers": "ice_climbers",
	"Ike": "ike",
	"Ivysaur": "ivysaur",
	"Jigglypuff": "jigglypuff",
	"King Dedede": "king_dedede",
	"Kirby": "kirby",
	"Link": "link",
	"Little Mac": "little_mac",
	"Lucario": "lucario",
	"Lucas": "lucas",
	"Lucina": "lucina",
	"Luigi": "luigi",
	"Mario": "mario",
	"Marth": "marth",
	"Mega Man": "mega_man",
	"Meta Knight": "meta_knight",
	"Mewtwo": "mewtwo",
	"Mii Brawler": "mii_brawler",
	"Mii Gunner": "mii_gunner",
	"Mii Swordfighter": "mii_swordfighter",
	"Mr. Game & Watch": "mr_game_watch",
	"Ness": "ness",
	"Olimar": "olimar",
	"Pac-Mac": "pacman",
	"Palutena": "palutena",
	"Peach": "peach",
	"Pichu": "pichu",
	"Pikachu": "pikachu",
	"Pit": "pit",
	"Pokemon Trainer": "pokemon_trainer",
	"R.O.B.": "rob",
	"Robin": "robin",
	"Rosalina & Luma": "rosalina_luma",
	"Roy": "roy",
	"Ryu": "ryu",
	"Samus": "samus",
	"Sheik": "sheik",
	"Shulk": "shulk",
	"Snake": "snake",
	"Sonic": "sonic",
	"Squirtle": "squirtle",
	"Toon Link": "toon_link",
	"Villager": "villager",
	"Wario": "wario",
	"Wii Fit Trainer": "wii_fit_trainer",
	"Wolf": "wolf",
	"Yoshi": "yoshi",
	"Young Link": "young_link",
	"Zelda": "zelda",
	"Zero Suit Samus": "zero_suit_samus"
};
