var countryCodes = {
	"Afghanistan": "flag flag-AF",
	"Aland Islands": "flag flag-AX",
	"Albania": "flag flag-AL",
	"Algeria": "flag flag-DZ",
	"American Samoa": "flag flag-AS",
	"Andorra": "flag flag-AD",
	"Angola": "flag flag-AO",
	"Anguilla": "flag flag-AI",
	"Antarctica": "flag flag-AQ",
	"Antigua And Barbuda": "flag flag-AG",
	"Argentina": "flag flag-AR",
	"Armenia": "flag flag-AM",
	"Aruba": "flag flag-AW",
	"Australia": "flag flag-AU",
	"Austria": "flag flag-AT",
	"Azerbaijan": "flag flag-AZ",
	"Bahamas": "flag flag-BS",
	"Bahrain": "flag flag-BH",
	"Bangladesh": "flag flag-BD",
	"Barbados": "flag flag-BB",
	"Belarus": "flag flag-BY",
	"Belgium": "flag flag-BE",
	"Belize": "flag flag-BZ",
	"Benin": "flag flag-BJ",
	"Bermuda": "flag flag-BM",
	"Bhutan": "flag flag-BT",
	"Bolivia": "flag flag-BO",
	"Bosnia And Herzegovina": "flag flag-BA",
	"Botswana": "flag flag-BW",
	"Bouvet Island": "flag flag-BV",
	"Brazil": "flag flag-BR",
	"British Indian Ocean Territory": "flag flag-IO",
	"Brunei Darussalam": "flag flag-BN",
	"Bulgaria": "flag flag-BG",
	"Burkina Faso": "flag flag-BF",
	"Burundi": "flag flag-BI",
	"Cambodia": "flag flag-KH",
	"Cameroon": "flag flag-CM",
	"Canada": "flag flag-CA",
	"Cape Verde": "flag flag-CV",
	"Cayman Islands": "flag flag-KY",
	"Central African Republic": "flag flag-CF",
	"Chad": "flag flag-TD",
	"Chile": "flag flag-CL",
	"China": "flag flag-CN",
	"Christmas Island": "flag flag-CX",
	"Cocos (Keeling) Islands": "flag flag-CC",
	"Colombia": "flag flag-CO",
	"Comoros": "flag flag-KM",
	"Congo": "flag flag-CG",
	"Congo, Democratic Republic": "flag flag-CD",
	"Cook Islands": "flag flag-CK",
	"Costa Rica": "flag flag-CR",
	"Cote D'Ivoire": "flag flag-CI",
	"Croatia": "flag flag-HR",
	"Cuba": "flag flag-CU",
	"Cyprus": "flag flag-CY",
	"Czech Republic": "flag flag-CZ",
	"Denmark": "flag flag-DK",
	"Djibouti": "flag flag-DJ",
	"Dominica": "flag flag-DM",
	"Dominican Republic": "flag flag-DO",
	"Ecuador": "flag flag-EC",
	"Egypt": "flag flag-EG",
	"El Salvador": "flag flag-SV",
	"Equatorial Guinea": "flag flag-GQ",
	"Eritrea": "flag flag-ER",
	"Estonia": "flag flag-EE",
	"Ethiopia": "flag flag-ET",
	"Falkland Islands (Malvinas)": "flag flag-FK",
	"Faroe Islands": "flag flag-FO",
	"Fiji": "flag flag-FJ",
	"Finland": "flag flag-FI",
	"France": "flag flag-FR",
	"French Guiana": "flag flag-GF",
	"French Polynesia": "flag flag-PF",
	"French Southern Territories": "flag flag-TF",
	"Gabon": "flag flag-GA",
	"Gambia": "flag flag-GM",
	"Georgia": "flag flag-GE",
	"Germany": "flag flag-DE",
	"Ghana": "flag flag-GH",
	"Gibraltar": "flag flag-GI",
	"Greece": "flag flag-GR",
	"Greenland": "flag flag-GL",
	"Grenada": "flag flag-GD",
	"Guadeloupe": "flag flag-GP",
	"Guam": "flag flag-GU",
	"Guatemala": "flag flag-GT",
	"Guernsey": "flag flag-GG",
	"Guinea": "flag flag-GN",
	"Guinea-Bissau": "flag flag-GW",
	"Guyana": "flag flag-GY",
	"Haiti": "flag flag-HT",
	"Heard Island & Mcdonald Islands": "flag flag-HM",
	"Holy See (Vatican City State)": "flag flag-VA",
	"Honduras": "flag flag-HN",
	"Hong Kong": "flag flag-HK",
	"Hungary": "flag flag-HU",
	"Iceland": "flag flag-IS",
	"India": "flag flag-IN",
	"Indonesia": "flag flag-ID",
	"Iran, Islamic Republic Of": "flag flag-IR",
	"Iraq": "flag flag-IQ",
	"Ireland": "flag flag-IE",
	"Isle Of Man": "flag flag-IM",
	"Israel": "flag flag-IL",
	"Italy": "flag flag-IT",
	"Jamaica": "flag flag-JM",
	"Japan": "flag flag-JP",
	"Jersey": "flag flag-JE",
	"Jordan": "flag flag-JO",
	"Kazakhstan": "flag flag-KZ",
	"Kenya": "flag flag-KE",
	"Kiribati": "flag flag-KI",
	"North Korea": "flag flag-KP",
	"South Korea": "flag flag-KR",
	"Kuwait": "flag flag-KW",
	"Kyrgyzstan": "flag flag-KG",
	"Lao People's Democratic Republic": "flag flag-LA",
	"Latvia": "flag flag-LV",
	"Lebanon": "flag flag-LB",
	"Lesotho": "flag flag-LS",
	"Liberia": "flag flag-LR",
	"Libya": "flag flag-LY",
	"Liechtenstein": "flag flag-LI",
	"Lithuania": "flag flag-LT",
	"Luxembourg": "flag flag-LU",
	"Macao": "flag flag-MO",
	"Macedonia": "flag flag-MK",
	"Madagascar": "flag flag-MG",
	"Malawi": "flag flag-MW",
	"Malaysia": "flag flag-MY",
	"Maldives": "flag flag-MV",
	"Mali": "flag flag-ML",
	"Malta": "flag flag-MT",
	"Marshall Islands": "flag flag-MH",
	"Martinique": "flag flag-MQ",
	"Mauritania": "flag flag-MR",
	"Mauritius": "flag flag-MU",
	"Mayotte": "flag flag-YT",
	"Mexico": "flag flag-MX",
	"Micronesia, Federated States Of": "flag flag-FM",
	"Moldova": "flag flag-MD",
	"Monaco": "flag flag-MC",
	"Mongolia": "flag flag-MN",
	"Montenegro": "flag flag-ME",
	"Montserrat": "flag flag-MS",
	"Morocco": "flag flag-MA",
	"Mozambique": "flag flag-MZ",
	"Myanmar": "flag flag-MM",
	"Namibia": "flag flag-NA",
	"Nauru": "flag flag-NR",
	"Nepal": "flag flag-NP",
	"Netherlands": "flag flag-NL",
	"Netherlands Antilles": "flag flag-AN",
	"New Caledonia": "flag flag-NC",
	"New Zealand": "flag flag-NZ",
	"Nicaragua": "flag flag-NI",
	"Niger": "flag flag-NE",
	"Nigeria": "flag flag-NG",
	"Niue": "flag flag-NU",
	"Norfolk Island": "flag flag-NF",
	"Northern Mariana Islands": "flag flag-MP",
	"Norway": "flag flag-NO",
	"Oman": "flag flag-OM",
	"Pakistan": "flag flag-PK",
	"Palau": "flag flag-PW",
	"Palestinian Territory, Occupied": "flag flag-PS",
	"Panama": "flag flag-PA",
	"Papua New Guinea": "flag flag-PG",
	"Paraguay": "flag flag-PY",
	"Peru": "flag flag-PE",
	"Philippines": "flag flag-PH",
	"Pitcairn": "flag flag-PN",
	"Poland": "flag flag-PL",
	"Portugal": "flag flag-PT",
	"Puerto Rico": "flag flag-PR",
	"Qatar": "flag flag-QA",
	"Reunion": "flag flag-RE",
	"Romania": "flag flag-RO",
	"Russian Federation": "flag flag-RU",
	"Rwanda": "flag flag-RW",
	"Saint Barthelemy": "flag flag-BL",
	"Saint Helena": "flag flag-SH",
	"Saint Kitts And Nevis": "flag flag-KN",
	"Saint Lucia": "flag flag-LC",
	"Saint Martin": "flag flag-MF",
	"Saint Pierre And Miquelon": "flag flag-PM",
	"Saint Vincent And Grenadines": "flag flag-VC",
	"Samoa": "flag flag-WS",
	"San Marino": "flag flag-SM",
	"Sao Tome And Principe": "flag flag-ST",
	"Saudi Arabia": "flag flag-SA",
	"Senegal": "flag flag-SN",
	"Serbia": "flag flag-RS",
	"Seychelles": "flag flag-SC",
	"Sierra Leone": "flag flag-SL",
	"Singapore": "flag flag-SG",
	"Slovakia": "flag flag-SK",
	"Slovenia": "flag flag-SI",
	"Solomon Islands": "flag flag-SB",
	"Somalia": "flag flag-SO",
	"South Africa": "flag flag-ZA",
	"South Georgia And Sandwich Islands": "flag flag-GS",
	"Spain": "flag flag-ES",
	"Sri Lanka": "flag flag-LK",
	"Sudan": "flag flag-SD",
	"Suriname": "flag flag-SR",
	"Svalbard And Jan Mayen": "flag flag-SJ",
	"Swaziland": "flag flag-SZ",
	"Sweden": "flag flag-SE",
	"Switzerland": "flag flag-CH",
	"Syrian Arab Republic": "flag flag-SY",
	"Taiwan": "flag flag-TW",
	"Tajikistan": "flag flag-TJ",
	"Tanzania": "flag flag-TZ",
	"Thailand": "flag flag-TH",
	"Timor-Leste": "flag flag-TL",
	"Togo": "flag flag-TG",
	"Tokelau": "flag flag-TK",
	"Tonga": "flag flag-TO",
	"Trinidad And Tobago": "flag flag-TT",
	"Tunisia": "flag flag-TN",
	"Turkey": "flag flag-TR",
	"Turkmenistan": "flag flag-TM",
	"Turks And Caicos Islands": "flag flag-TC",
	"Tuvalu": "flag flag-TV",
	"Uganda": "flag flag-UG",
	"Ukraine": "flag flag-UA",
	"United Arab Emirates": "flag flag-AE",
	"United Kingdom": "flag flag-GB",
	"United States": "flag flag-US",
	"United States Outlying Islands": "flag flag-UM",
	"Uruguay": "flag flag-UY",
	"Uzbekistan": "flag flag-UZ",
	"Vanuatu": "flag flag-VU",
	"Venezuela": "flag flag-VE",
	"Viet Nam": "flag flag-VN",
	"Virgin Islands, British": "flag flag-VG",
	"Virgin Islands, U.S.": "flag flag-VI",
	"Wallis And Futuna": "flag flag-WF",
	"Western Sahara": "flag flag-EH",
	"Yemen": "flag flag-YE",
	"Zambia": "flag flag-ZM",
	"Zimbabwe": "flag flag-ZW",
	"None": "flag flag-XX",
	"Alabama": "state state-AL",
	"Alaska": "state state-AK",
	"Arizona": "state state-AZ",
	"Arkansas": "state state-AR",
	"California": "state state-CA",
	"Colorado": "state state-CO",
	"Connecticut": "state state-CT",
	"Delaware": "state state-DE",
	"District of Columbia": "state state-DC",
	"Florida": "state state-FL",
	"Georgia": "state state-GA",
	"Hawaii": "state state-HI",
	"Idaho": "state state-ID",
	"Illinois": "state state-IL",
	"Indiana": "state state-IN",
	"Iowa": "state state-IA",
	"Kansas": "state state-KS",
	"Kentucky": "state state-KY",
	"Louisiana": "state state-LA",
	"Maine": "state state-ME",
	"Maryland": "state state-MD",
	"Massachusetts": "state state-MA",
	"Michigan": "state state-MI",
	"Minnesota": "state state-MN",
	"Mississippi": "state state-MS",
	"Missouri": "state state-MO",
	"Montana": "state state-MT",
	"Nebraska": "state state-NE",
	"Nevada": "state state-NV",
	"New Hampshire": "state state-NH",
	"New Jersey": "state state-NJ",
	"New Mexico": "state state-NM",
	"New York": "state state-NY",
	"North Carolina": "state state-NC",
	"North Dakota": "state state-ND",
	"Ohio": "state state-OH",
	"Oklahoma": "state state-OK",
	"Oregon": "state state-OR",
	"Pennsylvania": "state state-PA",
	"Rhode Island": "state state-RI",
	"South Carolina": "state state-SC",
	"South Dakota": "state state-SD",
	"Tennessee": "state state-TN",
	"Texas": "state state-TX",
	"Utah": "state state-UT",
	"Vermont": "state state-VT",
	"Virginia": "state state-VA",
	"Washington": "state state-WA",
	"West Virginia": "state state-WV",
	"Wisconsin": "state state-WI",
	"Wyoming": "state state-WY"
};
